name: Publish Artifact

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  upload_to_maven_central:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Check linting
        run: mvn git-code-format:validate-code-format

      - name: Test
        run: mvn --batch-mode --update-snapshots verify

      - name: Check project version
        run: .ci/scripts/check-version.sh

      - name: Install gpg key
        run: |
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | base64 --decode | gpg --batch --import

      - name: Maven deploy
        run: |
          mvn --no-transfer-progress --batch-mode \
            -Dgpg.passphrase='${{ secrets.GPG_KEY_PASS_PHRASE }}' \
            -DskipTests deploy -P release