name: Push Artifact

on:
  push:
    branches: [ main ]
  release:
    types: [released]

jobs:
  upload_to_maven_central:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git config
        run: |
          git config user.name "release-bot"
          git config user.email "<>"

      - name: Get version from tag
        id: get_version
        run: |
          releaseVersion="${GITHUB_REF/refs\/tags\//}"
          releaseVersion="${releaseVersion//v/}"
          echo "VERSION=$releaseVersion" >> $GITHUB_OUTPUT 

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Update version pom.xml
        run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Install gpg key
        run: cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | base64 --decode | gpg --batch --import

      - name: Publish
        run: |
          mvn --no-transfer-progress --batch-mode \
            -Dgpg.passphrase='${{ secrets.GPG_KEY_PASS_PHRASE }}' \
            deploy -P release

      - name: Bump version
        run: .ci/scripts/bump-version.sh